version: '3'
services:
  auto-encrypt-proxy:
    container_name: auto-encrypt-proxy
    build: .
    environment:
      - REDIS_HOST=redis
      #- STAGE=development
    ports:
      - "80:80"
      - "443:443"
    links:
      - redis
  redis:
    image: redis:latest
    container_name: redis
