version: '3'
services:
  auto-encrypt-proxy:
    build: .
    environment:
      - STAGE=development
      - REDIS_HOST=redis
    ports:
      - "80:80"
      - "443:443"
    links:
      - redis
  redis:
    image: redis:latest
    container_name: redis
